const $=id=>document.getElementById(id),fileInput=$('file');
const API='https://pogoapi.net/api/v1/',SPRITES='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/';
let catalog=[],movePools=[],fastMoves=[],chargedMoves=[];

fileInput.addEventListener('change',async()=>{const file=fileInput.files?.[0];if(!file)return;try{const bitmap=await createImageBitmap(file);showResult(analyze(bitmap));$('scanStatus').hidden=false;$('candidates').hidden=true;$('nameFallback').hidden=true;$('pokemonName').textContent='照合中…';await loadData();await classify(bitmap)}catch(e){$('scanStatus').hidden=true;$('nameFallback').hidden=false;$('pokemonName').textContent='判定できませんでした';$('recognition').textContent='手動検索できます';console.error(e);alert(`処理できませんでした: ${e.message}`)}});
$('pokemonSelect').addEventListener('change',e=>{const q=e.target.value.toLowerCase(),p=catalog.find(x=>x.name.toLowerCase()===q||x.ja===e.target.value);if(p)selectPokemon(p)});
$('again').addEventListener('click',()=>{fileInput.value='';$('result').hidden=true;$('picker').hidden=false;$('moves').hidden=true;$('candidates').hidden=true;scrollTo({top:0,behavior:'smooth'})});

async function loadData(){if(catalog.length)return;setProgress('全ポケモンと技データを取得中…');const [released,pools,fast,charged]=await Promise.all([get('released_pokemon.json'),get('current_pokemon_moves.json'),get('fast_moves.json'),get('charged_moves.json')]);movePools=pools;fastMoves=fast;chargedMoves=charged;const releasedIds=new Set(Object.values(released).map(x=>+x.id));const seen=new Set();catalog=pools.filter(x=>releasedIds.has(+x.pokemon_id)&&!seen.has(+x.pokemon_id)&&seen.add(+x.pokemon_id)).map(x=>({id:+x.pokemon_id,name:x.pokemon_name,sprite:`${SPRITES}${x.pokemon_id}.png`}));catalog.forEach(p=>{const o=document.createElement('option');o.value=p.name;$('pokemonList').append(o)});if(!catalog.length)throw Error('図鑑データを取得できません')}
async function get(path){const r=await fetch(API+path);if(!r.ok)throw Error(`データ取得エラー (${r.status})`);return r.json()}

async function classify(bitmap){const target=descriptorFromBitmap(bitmap,true),scores=[];let done=0;const queue=[...catalog];async function worker(){while(queue.length){const p=queue.shift();try{const img=await loadImage(p.sprite);p.desc=descriptorFromImage(img);scores.push({...p,score:distance(target,p.desc)})}catch{}done++;if(done%25===0)setProgress(`${done} / ${catalog.length}種類を照合中`)}}await Promise.all(Array.from({length:18},worker));scores.sort((a,b)=>a.score-b.score);const top=scores.slice(0,8);await Promise.all(top.map(localize));renderCandidates(top);$('scanStatus').hidden=true;$('candidates').hidden=false;$('nameFallback').hidden=false;$('pokemonName').textContent=top[0]?.ja||top[0]?.name||'候補なし';$('recognition').textContent='候補を確認してください'}
function setProgress(s){$('scanProgress').textContent=s}
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image;i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
function descriptorFromBitmap(b,crop){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d',{willReadFrequently:true});if(crop)x.drawImage(b,b.width*.12,b.height*.08,b.width*.76,b.height*.53,0,0,64,64);else x.drawImage(b,0,0,64,64);return histogram(x.getImageData(0,0,64,64).data,false)}
function descriptorFromImage(img){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,64,64);return histogram(x.getImageData(0,0,64,64).data,true)}
function histogram(data,alphaAware){const h=Array(20).fill(0);let n=0;for(let i=0;i<data.length;i+=4){if(alphaAware&&data[i+3]<80)continue;const r=data[i]/255,g=data[i+1]/255,b=data[i+2]/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,s=max?d/max:0;if(!alphaAware&&s<.18&&max>.72)continue;let hue=0;if(d){hue=max===r?((g-b)/d)%6:max===g?(b-r)/d+2:(r-g)/d+4;hue=(hue*60+360)%360}h[Math.min(11,hue/30|0)]+=s+.15;h[12+Math.min(3,s*4|0)]++;h[16+Math.min(3,max*4|0)]++;n++}return h.map(v=>v/Math.max(1,n))}
function distance(a,b){return Math.sqrt(a.reduce((s,v,i)=>s+(v-b[i])**2,0))}
async function localize(p){try{const [species,detail]=await Promise.all([fetch(`https://pokeapi.co/api/v2/pokemon-species/${p.id}`).then(r=>r.json()),fetch(`https://pokeapi.co/api/v2/pokemon/${p.id}`).then(r=>r.json())]);p.ja=species.names.find(n=>n.language.name==='ja-Hrkt')?.name||p.name;p.types=detail.types.map(t=>title(t.type.name));const o=document.createElement('option');o.value=p.ja;$('pokemonList').append(o)}catch{p.ja=p.name;p.types=[]}}
function renderCandidates(list){const grid=$('candidateGrid');grid.replaceChildren();list.forEach(p=>{const b=document.createElement('button');b.className='candidate';b.type='button';b.innerHTML=`<img src="${p.sprite}" alt=""><span>${escapeHtml(p.ja||p.name)}</span>`;b.onclick=()=>{grid.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectPokemon(p)};grid.append(b)})}
async function selectPokemon(p){if(!p.ja||!p.types)await localize(p);$('pokemonName').textContent=p.ja||p.name;$('recognition').textContent='選択済み';$('pokemonSelect').value=p.ja||p.name;showMoves(p)}
function showMoves(p){const pool=movePools.filter(x=>+x.pokemon_id===p.id);if(!pool.length){$('moves').hidden=true;return}const allFast=[...new Set(pool.flatMap(x=>[...x.fast_moves,...x.elite_fast_moves]))],allCharged=[...new Set(pool.flatMap(x=>[...x.charged_moves,...x.elite_charged_moves]))];const fs=allFast.map(n=>fastMoves.find(m=>m.name===n)).filter(Boolean).sort((a,b)=>scoreFast(b,p.types)-scoreFast(a,p.types));const cs=allCharged.map(n=>chargedMoves.find(m=>m.name===n)).filter(Boolean).sort((a,b)=>scoreCharged(b,p.types)-scoreCharged(a,p.types));$('moveTitle').textContent=`${p.ja||p.name}を活かすなら`;$('fastMove').textContent=fs[0]?.name||allFast[0]||'データなし';$('chargedMoves').textContent=cs.slice(0,2).map(x=>x.name).join(' ／ ')||allCharged.slice(0,2).join(' ／ ')||'データなし';$('moveNote').textContent='現在の技データから、タイプ一致・ダメージ効率・ゲージ効率を基準に自動算出した無料版の候補です。対戦リーグや相手によって最適解は変わります。';$('moves').hidden=false}
function scoreFast(m,types){const stab=types.includes(m.type)?1.2:1;return stab*((+m.power||0)/Math.max(1,+m.duration)*1000+(+m.energy_delta||0)/Math.max(1,+m.duration)*250)}
function scoreCharged(m,types){const stab=types.includes(m.type)?1.2:1;return stab*((+m.power||0)/Math.max(1,Math.abs(+m.energy_delta||100))*10+(+m.power||0)/Math.max(1,+m.duration)*1000)}
function title(s){return s.charAt(0).toUpperCase()+s.slice(1)}function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}

function analyze(bitmap){const w=600,h=Math.round(bitmap.height*w/bitmap.width),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(bitmap,0,0,w,h);const p=x.getImageData(0,0,w,h).data,rows=[];for(let y=h*.735|0;y<h*.89;y++){let first=-1,last=-1,count=0;for(let xx=w*.09|0;xx<w*.5;xx++){const i=(y*w+xx)*4;if(isBar(p[i],p[i+1],p[i+2])){if(first<0)first=xx;last=xx;count++}}if(first>w*.105&&first<w*.15&&count>w*.075&&last-first>w*.11)rows.push({y,first,last,count})}const groups=[];for(const row of rows){const g=groups.at(-1);if(!g||row.y>g.at(-1).y+1)groups.push([row]);else g.push(row)}const bars=groups.filter(g=>g.length>=4).map(g=>g.reduce((a,b)=>b.count>a.count?b:a)).filter(b=>b.y>h*.75).slice(0,3);if(bars.length!==3)throw Error(`評価バーを3本検出できませんでした (${bars.length}本)`);const vals=bars.map(b=>Math.max(0,Math.min(15,Math.round(Math.max(0,Math.min(1,(b.last-w*.118+1)/(w*.465-w*.118)))*15))));drawPreview(bitmap,bars,h);return vals}
function isBar(r,g,b){return r>210&&g>105&&g<205&&b<145&&r-g>35||r>195&&g>75&&g<165&&b>75&&b<175&&r-g>45}
function drawPreview(bitmap,bars,h){const o=$('preview');o.width=600;o.height=252;const x=o.getContext('2d');x.drawImage(bitmap,0,bitmap.height*.72,bitmap.width,bitmap.height*.2,0,0,o.width,o.height);x.strokeStyle='#00e5ff';x.lineWidth=3;x.setLineDash([8,5]);bars.forEach(b=>{const y=(b.y-h*.72)/(h*.2)*o.height;x.beginPath();x.moveTo(o.width*.108,y);x.lineTo(o.width*.475,y);x.stroke()})}
function showResult([a,d,h]){const total=a+d+h;$('percent').textContent=`${Math.round(total/45*100)}%`;$('grade').textContent=total===45?'4★':total>=37?'3★':total>=30?'2★':total>=23?'1★':'0★';[['attack',a],['defense',d],['hp',h]].forEach(([n,v])=>{$(`${n}Text`).textContent=`${v} / 15`;$(`${n}Bar`).style.width=`${v/15*100}%`});$('picker').hidden=true;$('result').hidden=false;$('result').scrollIntoView({behavior:'smooth'})}
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js');
